services:
  identity-service:
    container_name: identity-service
    image: jameskagunga254/identity-service:latest
    restart: always
    environment:
      - PORT=3001
    expose:
      - 3001
    ports:
      - 3001:3001
    networks:
      - identity_nw
networks:
  identity_nw:
    driver: bridge
